spring:
  application:
    name: gateway-pdv
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:wipay}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/auth/realms/gateway}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: ${SERVER_PORT:8082}
  ssl:
    enabled: false
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Configurações dos provedores de pagamento
cielo:
  api:
    url: ${CIELO_API_URL:https://apisandbox.cieloecommerce.cielo.com.br}
  merchant:
    id: ${CIELO_MERCHANT_ID:your_merchant_id}
    key: ${CIELO_MERCHANT_KEY:your_merchant_key}
  environment: ${CIELO_ENVIRONMENT:SANDBOX}

paypal:
  api:
    url: ${PAYPAL_API_URL:https://api-m.sandbox.paypal.com}
  client:
    id: ${PAYPAL_CLIENT_ID:your_client_id}
    secret: ${PAYPAL_CLIENT_SECRET:your_client_secret}

stripe:
  api:
    key: ${STRIPE_API_KEY:your_stripe_api_key}
    url: ${STRIPE_API_URL:https://api.stripe.com}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  packages-to-scan: com.wipay.gateway.controller
  paths-to-match: /**
